---
- name: Ensure python3-venv is installed
  ansible.builtin.apt:
    name: python3-venv
    state: present

- name: Create a virtual environment
  ansible.builtin.command: python3 -m venv /opt/ansible_venv
  args:
    creates: /opt/ansible_venv

- name: Ensure pip is installed in the virtual environment
  ansible.builtin.pip:
    name: pip
    executable: /opt/ansible_venv/bin/pip

- name: Ensure kubernetes is installed in the virtual environment
  ansible.builtin.pip:
    name: kubernetes
    executable: /opt/ansible_venv/bin/pip
